version: "3.3"
services:
  rabbitmq:
    image: rabbitmq:3.7.5-management
    container_name: rabbitmq-container
    network_mode: "host"
    hostname: localhost
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_VHOST:
    ports:
      - 5672:5672
      - 15672:15672

  mysqlservice:
    image: mysql:latest
    container_name: mysql-container
    restart: always
    network_mode: "host"
    hostname: localhost
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_USERNAME: authuser
      MYSQL_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  mongodbservice:
    image: mongo:latest
    container_name: mongo-container
    network_mode: host
    hostname: localhost
    ports:
      - 27017:27017

  user-service:
    container_name: user-service
    build: user-service/
    hostname: localhost
    network_mode: host
    ports:
      - 8888:8888
    depends_on:
      - mysqlservice
    restart: always

  soulmate-service:
    container_name: soulmate-service
    build: soulmate-service/
    hostname: localhost
    network_mode: host
    ports:
      - 8088:8088
    depends_on:
      - mongodbservice
    restart: always



